platform :ios, '6.0'
pod 'RestKit', '~> 0.24.0'
pod 'RKXMLReaderSerialization', :git => 'https://github.com/RestKit/RKXMLReaderSerialization.git', :branch => 'master'
pod 'CocoaLumberjack'
pod "TSMessages"